<?php

use Drupal\drupal_extractor\Extractors\Entities;

//1°
/**
 * drupal_extractor_preprocess_html
 *
 * @param [type] $variables
 * @author chr1sp1n-dev <chr1sp1n.dev@gmail.com>
 */
function drupal_extractor_preprocess_node(&$variables) {

}

//2°
/**
 * drupal_extractor_preprocess_html
 *
 * @param [type] $variables
 * @author chr1sp1n-dev <chr1sp1n.dev@gmail.com>
 */
function drupal_extractor_preprocess_html(&$variables) {

}

//3°
/**
 * drupal_extractor_preprocess_page
 *
 * @param [type] $variables
 * @author chr1sp1n-dev <chr1sp1n.dev@gmail.com>
 */
function drupal_extractor_preprocess_page(&$variables) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $data = Entities\Node::get();
    $variables['node_fields'] = $data;
    var_dump($variables['node_fields']);
    var_dump('TEST');
  }

}
